# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#title        : Nicholas Piercy's Website
logo          : "/assets/images/NP_Logo.png"
masthead_title: "Nicholas Piercy"
email         :
description   : >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here.
  You can edit this line in _config.yml. 
  It will appear in your document head meta (for Google search results) and in your feed.xml site description.

twitter_username	: username
github_username      	: NicGyver1

search               	: true

# Build settings
markdown     	      	: kramdown
remote_theme          	: "mmistakes/minimal-mistakes@4.26.2" #mmistakes/minimal-mistakes
minimal_mistakes_skin	: "dirt" # "air", "aqua", "default", "dark", "contrast", "neon", "mint", "plum", "sunrise"

# Outputting
permalink    	      	: /:categories/:title/
timezone     		: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Pagination with jekyll-paginate
paginate     		: 5 # amount of posts to show
paginate_path		: /page:num/


# Reading Files
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. 
# Create a custom list to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


author:
  name   : "Nicholas Piercy"
  avatar : "/assets/images/Nicholas_Piercy_Headshot_11-21-2018.jpg"
  bio    : "Graduate student in the Mechanical and Materials Engineering department at The University of Nebraska - Lincoln." # "My awesome biography constrained to a sentence or two goes here."
  
  links  :
    - label: "Website"
      icon : "fas fa-fw fa-link"
      url  : "nicholaspiercy.com"
    - label: "Google Scholar"
      icon : "fa-brands fa-google-scholar"
      url  : "https://scholar.google.com/citations?user=JSAi7N8AAAAJ&hl=en&oi=ao"
    - label: "GitHub"
      icon : "fab fa-fw fa-github"
      url  : "https://github.com/NicGyver1"
    - label: "LinkedIn"
      icon : "fa-brands fa-linkedin"
      url  : "https://linkedin.com/in/piercynicholas"

footer:
  links:
    - label: "Google Scholar"
      icon : "fa-brands fa-google-scholar"
      url  : "https://scholar.google.com"
    - label: "GitHub"
      icon : "fab fa-fw fa-github"
      url  : "https://github.com/"
    - label: "LinkedIn"
      icon : "fa-brands fa-linkedin"
      url  : "https://linkedin.com"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
